### ISSUE TITLE
Request for Details on Gemma-2B and DeepSeekMath-7B-Instruct Models

### ISSUE THREAD

**Issue by brightest66** [SparkJiao/dpo-trajectory-reasoning#1]
Hello and congratulations on your impressive work in mathematical reasoning!

While reproducing the experiments, I noticed that the sources for the Gemma-2B and DeepSeekMath-7B-Instruct models, which are trained on a subset of MetaMath, were not included. Could you provide additional details on these models or point to any available resources?

Thank you very much for your assistance, and again, congratulations on the work!

**Comment by SparkJiao** [comment]
Hi, here are the checkpoints for the models shown in the paper:

Gemma-2b-It-SFT:
https://huggingface.co/chitanda/gemma.2b.it.meta_math_distil.H100.w4.v1.0

Gemma-2b-It-DPO:
https://huggingface.co/chitanda/gemma.2b.it.meta_math_rap.dpo.H100.w4.v1.1.fix.s42

The config for reproducing the pDPO experiments on Gemma should be:
https://github.com/SparkJiao/dpo-trajectory-reasoning/blob/main/conf/exp/dpo/gemma/meta_math_rap/step_dpo_v1_0.yaml
The checkpoints are not uploaded yet. 

For deepseek-math, we did not further fine-tune it on MetaMath. You can simply use deepseek-math-instruct for further experiments.

**Comment by brightest66** [comment]
已收到您的来信，谢谢！
