### ISSUE TITLE
Request for more Details on Training the Reward Model

### ISSUE THREAD

**Issue by brightest66** [SparkJiao/dpo-trajectory-reasoning#2]
Hi,

I am currently attempting to reproduce the experiments detailed in the section titled "Process Rewards Annotating (Taking LogiQA-v2 as an Example)" from your README.md file. However, as I reach Step 5, I have observed that there is no script available for training the reward model (RM). Could you please provide more information about the RM training process? Specifically, it would be extremely beneficial if you could share details about any files associated with the RM training or provide a script similar to those previously shared.

I have attempted to run the following script:
```bash
deepspeed trainer_base_ds_mul.py -cp conf/exp/reward/logiqav2 -cn llama2_7b_70bdistil_prm_v2_0
```
but it failed to execute. Perhaps there is an issue with my Python environment setup (even though I installed it according to the requirements.txt) or I might have misunderstood the code structure and executed the wrong script. 

Thank you very much for your assistance. Please excuse my limited coding experience.

**Comment by SparkJiao** [comment]
Please show me the error message.

**Comment by brightest66** [comment]
Ubuntu 20.04.1
nvidia 4090 * 2
cuda 12.4

flash-attn: 2.3.3
vllm: 0.2.5
transformers: 4.36.1
deepspeed: 0.12.2

partial output below:  Thanks for your help!

```bash
[2024-11-07 20:47:17,327][FK][WARNING] - Error locating target 'models.llama.LlamaModelForSequenceClassification.from_pretrained', see chained exception above.
full_key: model
Traceback (most recent call last):
  File "/home/work/anaconda3/envs/reasoning_dpo/lib/python3.9/site-packages/hydra/_internal/utils.py", line 639, in _locate
    obj = getattr(obj, part)
    obj = getattr(obj, part)AttributeError
: module 'models' has no attribute 'llama'
AttributeError
During handling of the above exception, another exception occurred:

···
ImportErrorTraceback (most recent call last):
:   File "/home/data/daiqun/dpo-trajectory-reasoning-main/trainer_base_ds_mul.py", line 328, in main
Error loading 'models.llama.LlamaModelForSequenceClassification.from_pretrained':
ImportError('/home/work/anaconda3/envs/reasoning_dpo/lib/python3.9/site-packages/flash_attn_2_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK3c105Error4whatEv')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/data/daiqun/dpo-trajectory-reasoning-main/trainer_base_ds_mul.py", line 328, in main
    model = hydra.utils.call(cfg.model, cfg.model_name_or_path, state_dict=pretrain_state_dict)
  File "/home/work/anaconda3/envs/reasoning_dpo/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 325, in instantiate_node
    return instantiate_node(
  File "/home/work/anaconda3/envs/reasoning_dpo/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 325, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/work/anaconda3/envs/reasoning_dpo/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'models.llama.LlamaModelForSequenceClassification.from_pretrained', see chained exception above.
full_key: model
    
···
Traceback (most recent call last):
  File "/home/work/anaconda3/envs/reasoning_dpo/lib/python3.9/site-packages/hydra/_internal/utils.py", line 639, in _locate
    obj = getattr(obj, part)
AttributeError: module 'models' has no attribute 'llama'

During handling of the above exception, another exception occurred:

···
Traceback (most recent call last):
  File "/home/data/daiqun/dpo-trajectory-reasoning-main/trainer_base_ds_mul.py", line 426, in <module>
    raise ImportError(
ImportError: Error loading 'models.llama.LlamaModelForSequenceClassification.from_pretrained':
ImportError('/home/work/anaconda3/envs/reasoning_dpo/lib/python3.9/site-packages/flash_attn_2_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK3c105Error4whatEv')

The above exception was the direct cause of the following exception:

···
hydra.errors.InstantiationException: Error locating target 'models.llama.LlamaModelForSequenceClassification.from_pretrained', see chained exception above.
full_key: model
```

**Comment by SparkJiao** [comment]
Maybe you can first reinstall flash-attention following https://github.com/Dao-AILab/flash-attention

If it still does not work, change the attn_implementation [here](https://github.com/SparkJiao/dpo-trajectory-reasoning/blob/main/conf/exp/reward/logiqav2/llama2_7b_70bdistil_prm_v2_0.yaml#L42) from `flash_attention_2` to `sdpa` or `eager`.

**Comment by brightest66** [comment]
Hi, Can you release the folder named `llama2.7b.chat.logiqav2.70b-distil.prm.fix_hack.H100.w4.v2.0.s42`?I didn't seem to find it on https://huggingface.co/chitanda.

Thanks for you help!

**Comment by SparkJiao** [comment]
It should be public now.

**Comment by brightest66** [comment]
Can you release `llama2.7b.chat.reclor.gpt351106.prm.fix_hack.H100.w8.v1.3.s42`?

Thanks for you help!

**Comment by SparkJiao** [comment]
@brightest66 Hi, `llama2.7b.chat.reclor.gpt351106.prm.fix_hack.H100.w8.v1.3.s42` should be available now.

**Comment by brightest66** [comment]
Could you please release `llama2.7b.chat.reclor.gpt351106.prm.fix_hack.H100.w8.v2.0.s42`?
Thanks for you help! And sorry for any inconvenience my repeated requests might cause.

**Comment by SparkJiao** [comment]
@brightest66 Hi, it should be public now, thanks.

**Comment by brightest66** [comment]
Hi, while reviewing your code for training the LLama-2-7B model on the reclor dataset, could you please explain why the `Action` part is not considered when calculating the accumulated production of the process rewards assigned at each intermediate step?

`probs = torch.tensor([prob.item() for prob, step_type in zip(probs, step_types) if step_type != "Action"])` 
[More details about the above code](https://github.com/SparkJiao/dpo-trajectory-reasoning/blob/cba62851ee443c16431a67cc544dfacc210c9a65/scripts/best_of_filter_by_reward_v2.2.1.py#L135)

**Comment by SparkJiao** [comment]
After I have reviewed the sampled responses, I found that `Action` is usually a follow-up of `Thought`, which means that it hardly obey its own idea of how to perform the next step. As a result, we can remove the consideration of `Action` and focus on `Observation` and `Thought` only to avoid potential bias.

**Comment by brightest66** [comment]
Please release `llama2.7b.chat.logiqav2.70b-distil.prm.fix_hack.A100.w4.v1.2.s42`?
Thanks for you help!

**Comment by SparkJiao** [comment]
done

**Comment by SparkJiao** [comment]
Done.

**Comment by brightest66** [comment]
Hi, when I was reviewing the experimental results of the `step.DPO` model trained on the LogiQA-v2.0 dataset that you released (specifically:
`https://huggingface.co/chitanda/llama2.7b.chat.logiqav2.70b-distil.step.dpo.fix_hack.H100.w4.v1.0.th.s43`,
`https://huggingface.co/chitanda/llama2.7b.chat.logiqav2.70b-distil.step.dpo.fix_hack.H100.w4.v1.0.th.s42`,
`https://huggingface.co/chitanda/llama2.7b.chat.logiqav2.70b-distil.step.dpo.fix_hack.A100.w4.v1.0.th.s44`),
I noticed that those model's best experimental results on the LogiQA-v2.0 test set are slightly higher than the results published in the paper(I have compute the average results of 3). Could you please tell me which checkpoint you selected and the basis for your selection?

Additionally, according to the experimental results you have shared, the models mentioned above perform above 70% on the ReClor validation set but show **zero** on the test set. This is because the standard answers for the test set are not publicly available. However, the experimental results on ReClor that you published in the paper are around 60%. Could you please provide more details about this?

Thanks for you help!

**Comment by SparkJiao** [comment]
The standard workflow for testing model is reporting the results on test set of the checkpoints achieving the best performance on the validation set. You are not allowed to use the test set to adjust the hyper-parameter or select model.

For ReClor, in order to obtain the results on the test set, please submit the prediction file to their leaderboard.
