### ISSUE TITLE
What is the specific process of constructing DPO's training data? Why is there no relevant data in the provided link?

### ISSUE THREAD

**Issue by LeiyanGithub** [SparkJiao/dpo-trajectory-reasoning#3]
<img width="914" alt="image" src="https://github.com/user-attachments/assets/95369545-b2a0-4f18-aec5-613519121b13">

**Comment by LeiyanGithub** [comment]
Where can I get the training data for the process reward model? 
<img width="236" alt="image" src="https://github.com/user-attachments/assets/eee48fd0-b136-4f7a-87a4-1b0250aebad4">

**Comment by SparkJiao** [comment]
Hi, for DPO training, please see [this script](https://github.com/SparkJiao/dpo-trajectory-reasoning/blob/main/scripts/construct_dpo_data_from_react_response_v1.1.py). The input file is the sampled responses from the policy model to be improved. 

For the huggingface repo, please check the **files and version** to see the contained data and weights.

**Comment by SparkJiao** [comment]
For all the data, you can find them according to the position specified in the config file.

For example, in [this config](https://github.com/SparkJiao/dpo-trajectory-reasoning/blob/main/conf/exp/dpo/reclor/llama2_7b_gpt351106_distil_step_dpo_v5_0.yaml), you can find the training data locates under

```
sft_model_dir: experiments/llama2.7b.chat.reclor.gpt35turbo1106.dpo-sft.H100.w4.v2.0/checkpoint-1200/
train_file: ${sft_model_dir}/reclor.react.train.0shot.sample10.tem0.7.v1.0.prm_v20_cp400_best_of_10.neg10.pos0.4.v2.2.1.(2,3).pair.product.full_only.json
```

Then, you can turn to the huggingface page to fine the sft model and data:

[https://huggingface.co/chitanda/llama2.7b.chat.reclor.gpt35turbo1106.dpo-sft.H100.w4.v2.0/tree/main/checkpoint-1200](https://huggingface.co/chitanda/llama2.7b.chat.reclor.gpt35turbo1106.dpo-sft.H100.w4.v2.0/tree/main/checkpoint-1200)

If some models are not available on huggingface hub, please let me know.

**Comment by SparkJiao** [comment]
Feel free to re-open this issue again if there are still any problems.
